### ISSUE TITLE
테스트 라이브러리 추가

### ISSUE THREAD

**Issue by rkdgusrnrlrl** [hyeongJuKim/MyBook#17]
## 목적
- 테스트를 위해 테스트 라이브러리가 필요
- 기본적으로 쓰는 테스트 라이브러리 보다 pytest 가 낫다고 함
  - [참조자료](https://cjh5414.github.io/why-pytest/)

## 상세 작업 작업
- pytest-django 설치
- `requirement.txt` 에 설치 된 라이브리러 기록
- 간단한 테스트 작성

**Comment by rkdgusrnrlrl** [comment]
@hyeongJuKim 우선 pytest 써보는 거 어떠함??

**Comment by hyeongJuKim** [comment]
좋은 생각입니다 ㅎㅎ
pytest 할 간단한 규칙도 같이 생각해서 wiki에 등록하면 좋을거같아요.
그리고 라이브러리 설치하면 잊지말고 `pip freeze > requirements.txt`  로 목록도 뽑아주세요 ㅎㅎ

**Comment by rkdgusrnrlrl** [comment]
@hyeongJuKim pytest 할 간단한 규칙은 없고 테스트 샘플 코드만 있으면 될 듯, `pip freeze > requirements.txt` 는 처리 하겠음 ㅋㅋ 그런건 풀리퀘 할떄 빠졌으면 리뷰 달아 줘 ㅋㅋ

**Comment by rkdgusrnrlrl** [comment]
위에 발생 했던 오류 해결 및 샘플 테스트 작성 및 테스트 코드 잘 돌아 가는 것 확인 해 이슈 닫음
