### ISSUE TITLE
AttributeError: 'User' object has no attribute 'USERNAME_FIELD' 에러 발생

### ISSUE THREAD

**Issue by rkdgusrnrlrl** [hyeongJuKim/MyBook#20]
## 상황
- User 모델 인스턴스를 print 하면 `AttributeError: 'User' object has no attribute 'USERNAME_FIELD'`

## 해결 방안
- User 모델에 USERNAME_FIELD 구현 하면 됨
- [user 모델 커스텀](https://docs.djangoproject.com/en/2.0/topics/auth/customizing/#specifying-a-custom-user-model)

**Comment by hyeongJuKim** [comment]
모델에 적용 완료 !
