### ISSUE TITLE
Github master 브랜치에 푸시 할 수 없게 막기

### ISSUE THREAD

**Issue by rkdgusrnrlrl** [hyeongJuKim/MyBook#22]
## 목적
- `master` 다이렉트로 push 가 들어가 리뷰 없이 들어감
- 그로 인해 여러 이슈들이 추가적으로 발생

## 상세 작업 내용
- Github 설정으로 `mater` 브랜치에는 꼭 Pull request 통해야 머지 될 수 있게 설정

**Comment by rkdgusrnrlrl** [comment]
- 아래 이미지를 참조 해서 진행 하면 될 듯
![image](https://user-images.githubusercontent.com/11402853/36826392-43e33a60-1d50-11e8-9520-63de23a10d82.png)

**Comment by hyeongJuKim** [comment]
알려준대로 설정해놨음 ㅎㅎ🤓
