### ISSUE TITLE
#24 pip install pkg-resources==0.0.0 오류 발생

### ISSUE THREAD

**Issue by hyeongJuKim** [hyeongJuKim/MyBook#25]
#24 pytest source pull 후에 pip install을 하면 오류 발생.

**Comment by hyeongJuKim** [comment]
requirements.txt에 pkg-resources==0.0.0를 제거하면 해결됨.
이 부분은 버그인 것 같음.

**Comment by rkdgusrnrlrl** [comment]
우선 master pull 한뒤 테스트 해보니 오류 없음
