### ISSUE TITLE
레파지토리 전체 디렉토리 구조 변경 요청

### ISSUE THREAD

**Issue by hyeongJuKim** [hyeongJuKim/MyBook#26]
- 보통 다른 레퍼지토리보다 한 디렉토리가 dept가 더 존재함.
- 모델 접근 할 때마자 계속해서 경로를 잘 찾기 못하는 현상 계속 발생.
- django admin에서도 `django.db.utils.OperationalError: no such table: book_user`과 같이 경로를 찾지 못함.
- SQLite 바라보는 path 설정을 바꿔도 되지만 다른 프로젝트들과 같이 디렉토리 변경 요청합니닷😀

![2018-03-03 2 46 43](https://user-images.githubusercontent.com/13251585/36931090-894baaee-1ef2-11e8-86e0-a5f6dce778d6.png)
settings.py의 sqlite가 base directory를 참조하고 있음.

![2018-03-03 2 46 48](https://user-images.githubusercontent.com/13251585/36931101-c0e19022-1ef2-11e8-8ba2-e57ab08b1fbe.png)

![2018-03-03 2 46 51](https://user-images.githubusercontent.com/13251585/36931108-cb6c6ddc-1ef2-11e8-9121-5e8edb2dde20.png)
확인 해보니 이렇게 base directory를 갖고 있음.

**Comment by rkdgusrnrlrl** [comment]
- django admin에서도 django.db.utils.OperationalError: no such table: book_user과 같이 경로를 찾지 못함.
- 위의 에러가 어떤 상황에서 발생 됐는지 설명이 필요 함

**Comment by hyeongJuKim** [comment]
- 지금 구조대로 진행.
- git clone 후 migrations 다시 해보니 정상 작동.
