### ISSUE TITLE
base template 만들기

### ISSUE THREAD

**Issue by hyeongJuKim** [hyeongJuKim/MyBook#32]
site main template 제작
- [x] urls.py 정의
- [x] base template 추가
- [x] index template 추가
- [x] (Bootstrap)
- [x] 기본 디자인 적용하기

**Comment by rkdgusrnrlrl** [comment]
기대하고 있겠음 ㅋㅋㅋ

**Comment by hyeongJuKim** [comment]
후덜덜...
말 그대로 기본 올릴거에요😁🤣

**Comment by rkdgusrnrlrl** [comment]
후지면 리젝 할꺼임 ㅋㅋㅋ :smiling_imp::smiling_imp::smiling_imp:
