### ISSUE TITLE
사용자 모델 개선

### ISSUE THREAD

**Issue by rkdgusrnrlrl** [hyeongJuKim/MyBook#33]
## 목적
- 아이디를 email 로 변경함
- 관리자 페이지 User 모델과 통합을 위해

## 작업내역
- email 필드를 추가 함
- User 모델 대체 하기 위해 구현 해야 할 함수 및 필드 구현
- 망하지 않기를 바라기 기도 :pray::pray::pray:

**Comment by hyeongJuKim** [comment]
코드 지켜보겠습니더🧐

**Comment by rkdgusrnrlrl** [comment]
머지 완료 돼서 해당 이슈 클로즈
