### ISSUE TITLE
책 수정 관련 수정 사항

### ISSUE THREAD

**Issue by rkdgusrnrlrl** [hyeongJuKim/MyBook#41]
https://github.com/hyeongJuKim/MyBook/pull/39#discussion_r174448762
- 참고 부탁
- 수정 페이지에서 user 가 등록이 안되 있어 무조건 0 번 user.name 이 보여짐

**Comment by hyeongJuKim** [comment]
엇?
user 필수항목인데
기존 데이터 날리시고
새로 해도 그런가요?

**Comment by rkdgusrnrlrl** [comment]
넵 그렇습니다. 혹시 모르니 너도 한번 확인 해봥 ㅎㅎ

**Comment by hyeongJuKim** [comment]
아이디빼면 입력이안되는데
필수값이라 ㅋㅋ

**Comment by rkdgusrnrlrl** [comment]
@hyeongJuKim  아이디는 당연 입력 했지 근데 상세 보기에는 잘 나오는데 수정 페이지에는 0 번 꺼 이름으로 나옴
암튼  UI 에서 해당 부분을 빼도되고 필드를 추가 해도 되고

**Comment by hyeongJuKim** [comment]
저는 문제가없는거같은데 ㅠㅠ

**Comment by rkdgusrnrlrl** [comment]
나중에 한번 다시 DB 초기화 하고 확인 해 보겠음 ㅠㅠ
