### ISSUE TITLE
사용자 상세 페이지 꾸며 주기

### ISSUE THREAD

**Issue by rkdgusrnrlrl** [hyeongJuKim/MyBook#45]
- 사용자 명, 닉네임, 이메일 보여짐
- 수정 버튼 필요(수정 페이지는 추가 하지 않음)

## 추가 논의가 필요
- 패스워드 변경은 어떻게 보여져야 할까?
- 내 책 정보 는 필요 없습니까?
  - 필요 하다면 어떤 정보를 보여주면 좋을까? 
     - 예) 갖은 책 혹은 읽은 책 => 프로그레스바로 전체 책어 몇권을 읽었나 보여줌

**Comment by rkdgusrnrlrl** [comment]
@hyeongJuKim 
![help!!!!!](https://i2.ruliweb.com/ori/17/11/20/15fd9c07f3f1ed55e.jpg)

**Comment by hyeongJuKim** [comment]
slack에서 논의합시닷🗣

**Comment by hyeongJuKim** [comment]
- 패스워드 변경은 어떻게 보여져야 할까?
->`디자인 https://goo.gl/bU26rf`에서 user page 참고
- 내 책 정보 는 필요 없습니까?
-> 내 책에 대한 관리는 `my page`라를 메뉴를 추가해서 관리할 예정임
 - 필요 하다면 어떤 정보를 보여주면 좋을까?
-> 등록한 책의 정보를 기반으로 다양한 통계를 내도록
ex1) 월별 책 등록 권 수 chart
ex2)갖고있는 책, 읽은 책 비율(프로그래스 바)

**Comment by rkdgusrnrlrl** [comment]
@hyeongJuKim  대략적으로 필요한 차트 내용들도 아래 링크에 추가 해주면 참고 해서 작업 함. 혹시 봐둔 차트 라이브러리 있음??
https://ovenapp.io/view/mBbrEb08nvxmw4MtgobGOK7dJZJk1aK6/CeLVb

**Comment by hyeongJuKim** [comment]
@rkdgusrnrlrl 아직 봐둔 차트라이브러리 없어요 ㅠㅠ

**Comment by rkdgusrnrlrl** [comment]
우선 머지 돼서 이슈 클로즈~~
