### ISSUE TITLE
풀리퀘 이쁘게 쓰기

### ISSUE THREAD

**Issue by rkdgusrnrlrl** [hyeongJuKim/MyBook#50]
@hyeongJuKim 풀리퀘 쓸 때  테스트 할 내용이랑 수정 사항도 썼는데 의미 있는 것 같음??

**Comment by hyeongJuKim** [comment]
@rkdgusrnrlrl 개꿀임.
저는 아직은  잘 못쓰는듯 ㅋㅋㅋ

**Comment by rkdgusrnrlrl** [comment]
나도 잘 못씀 ㅠㅠ PR의 사이즈를 줄이면 좋을 것 같은데, 우선 최대한 이쁘게 적고, 더 필요한 사항이 있으면 요청 해줘 나도 요청 하도록 할께 ㅎㅎ
혹시 뭔가 추가 로 적거나 할 부분이 있을까??

**Comment by hyeongJuKim** [comment]
풀리퀘 규칙 간단하게만 협의해서
위키에 등록하죠ㅎㅎ

**Comment by rkdgusrnrlrl** [comment]
좋음 ㅋㅋ 우선 테스트 목록 및 수정 혹은 작업 한 사항 적어 주고 참고 할 것 까지 적어주는 것 어떰??
너무 많나?? 아 이슈 번호 첫줄에 적어 주고 ㅎㅎ

**Comment by hyeongJuKim** [comment]
이런식으로요 ????

#이슈번호

### 작업내용
- 작업함
- 계속함
- 한번 더함

### 테스트 사항
- 잘되는지
- 작동하는지

**Comment by rkdgusrnrlrl** [comment]
:+1:  굳굳!!!
- 난 이정도면 될 것 같은데 내가 풀리퀘 달았을때 어떤 정보 더 주면 좋을 만한게 있음??
- 아 나 요번에 니꺼 풀리퀘 보면서 깨달은 건데 커밋도 중요한 것 같음 ㅠㅠ

**Comment by hyeongJuKim** [comment]
ㅋㅋㅋ 형이 커밋 잘 쪼개서 달길래
저도 쪼개서 달은거에요 ㅋㅋㅋㅋㅋ

**Comment by rkdgusrnrlrl** [comment]
ㅋㅋㅋ 나도 못지키는데 겁나 잘하네 
하다 보면 지나치게 많이 작업함 그럼 귀찮아서 그냥 파일단위로 쪼개서 함 ㅠㅠ
암튼 저번 풀리퀘는 리뷰 하기 좋았음 ㅎㅎ

**Comment by hyeongJuKim** [comment]
이쁘게 쓰고 있는거 같아서 닫겠음 ㅎㅎㅎㅎ
