### ISSUE TITLE
view에 세션 연동하기

### ISSUE THREAD

**Issue by hyeongJuKim** [hyeongJuKim/MyBook#57]
book이랑 user쪽 어느정도 밑그림은 그려진 것 같습니다.
이제 login해서 개발 진행해도 될것같음 ㅎㅎ
- 세션없이 세션권한 필요한 view에 접근시 로그인 페이지로 이동시키기.
  (로그인하면 다시 이전 view로 이동)
- book관련 view에도 세션정보로 책을 등록 가능하도록 변경
- 로그인 완료시 이전 페이지로 돌리기 (next)

**Comment by rkdgusrnrlrl** [comment]
혹시 로그인 한 사용자 어떻게 받아오는 지 앎?

**Comment by hyeongJuKim** [comment]
view에서요 ?
아니면  template에서 말하는건가요 ?

**Comment by rkdgusrnrlrl** [comment]
당연히 뷰 ㅎㅎ 뷰에서 꺼내면 템플릿에서는 쉽게 쓸 수 있자네 ㅎㅎ

**Comment by hyeongJuKim** [comment]
뷰에서 담지 않아도 템플릿에션 그냥 요런식으로 확인할수 있어요.
```  html
{{ user }}
{{ user.is_authenticated }}
{{ user.is_anonymous }}
{{ user.is_active }}
```

근데 뷰에서 체크할필요없이 `@login_required(login_url='login')` 요런거 걸면 되지 않을까요 ?

**Comment by rkdgusrnrlrl** [comment]
아 뷰에서 user 값을 받아서 처리 해야 할 수도 있을 것 같아서, 예를 들어 나의 책장(?) 의 템플릿에 책들을 내려줄때 뷰에서 세션에 있는 유저 정보로 Book 에 filter 를 줘야 하잖아

**Comment by rkdgusrnrlrl** [comment]
@hyeongJuKim  이거 완료 됐다고 생각하면 클로즈 해줭 ㅎㅎ
