### ISSUE TITLE
책 읽음상태 코드로 조회목록에서 쉽게 구분가도록 수정

### ISSUE THREAD

**Issue by hyeongJuKim** [hyeongJuKim/MyBook#59]
어떻게 하면 `책읽음 상태`로 한쉽게 구분 지을수있을까?
- 코드에 따른 색상 추가?

**Comment by rkdgusrnrlrl** [comment]
약간 todo 같은 스타일 어떰??

**Comment by hyeongJuKim** [comment]
좀 더 자세히 설명좀 해주세요 ㅋㅋㅋㅋ

**Comment by rkdgusrnrlrl** [comment]
todo 스타일 아래 같이
- [x] 책1
- [ ] 책2

**Comment by hyeongJuKim** [comment]
오 ㅋㅋ TODO방식???ㅎㅎ
근데 지금은 읽지않음,읽는중,읽음 이렇게 세가지라서 ㅠ
리스트 하단에 태그처럼 보여주고는 있어요 ㅎㅎ

**Comment by rkdgusrnrlrl** [comment]
@hyeonJuKim 읽을 책을 페이지 수나눠 테스크 처럼 만드는 거지 완료 하려면 읽은 소감 작성 하구 ㅋㅋ 집가서 아이디어를 뭔가 정리 해보겠음

**Comment by hyeongJuKim** [comment]
형 저기 위에 잘못 태그했네효 ㅎㅎ
모르는 분임....ㅎㅎㅎㅎ

**Comment by rkdgusrnrlrl** [comment]
ㅋㅋㅋㅋ 죄송합니다 ㅠㅠ
