### ISSUE TITLE
책도 미래에서 구매 할 수 있음 +ㅁ+)b

### ISSUE THREAD

**Issue by rkdgusrnrlrl** [hyeongJuKim/MyBook#71]
- 책 등록 시 현재 일자의 다음 날이여도 등록이 됨
- @hyeongJuKim  괜찮음??

**Comment by hyeongJuKim** [comment]
@rkdgusrnrlrl 앗 그걸 생각못했네요ㅋㅋㅋㅋㅋ
오늘 날짜 이후로는 설정하지 못하도록 수정하겠습니다.
